version: "3"

services:
  devops_insights_postgres:
    image: postgres:16.2-bullseye
    restart: always
    shm_size: 128mb
    environment:      
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"